### ISSUE TITLE
Datenquellen

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-statistik#2]
Folgende URLs stehen zum Abruf von Text/CSV-Daten zur Verfügung:

jeweils davor: https://statistiken.rrze.fau.de/webauftritte/logs/$DOMAINNAME/

./webalizer.hist
   Zugriffsdaten der letzten Monate, wie sie auf https://statistiken.rrze.fau.de/webauftritte/logs/DOMAINNAME gezeigt werden/

./agent_YYYYMM.tab
    Useragent-Daten des Jahres YYYY und Monat MM.  Daten nicht so ganz zuverlässig.

./err_YYYYMM.tab
    Fehler

./ref_YYYYMM.tab
   Referer

./search_YYYYMM.tab
    Suchrequests

./site_YYYYMM.tab
   Zugriffe von Quellen

./url_YYYYYMM.tab
   Zugriffszahlen je Seite.
   Entspricht den Inhalt aus ./url_YYYYYMM.html

./url_delta_YYYYMMTT.tab
   Unterschied der Zugriffe zum Vortrag TT auf je URL

./usage_YYYYMM.xml
     Entspricht dem Inhalt von usage_YYYYMM.html

**Comment by lukasniebler** [comment]
Dokumentiert auf wordpress.rrze.fau.de (s. https://github.com/lukasniebler/rrze-dokumentation/issues/60 )
